# -*- coding: utf-8 -*-
"""Deteksi_Pertanyaan_By_Me.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ypiA5Ynptkbh7qfqJMh0e0CO8C4zfUC

# DETEKSI **PERTANYAAN**
"""

import nltk
nltk.download('punkt')

"""# COBA-**1**"""

from nltk.tokenize import word_tokenize

"""
kata_tanya = ["what", "why", "when", "where", "who",
             "name", "is", "how", "do", "does",
             "which", "are", "could", "would",
             "should", "has", "have", "whom", "whose", "don't"]
"""

kata_tanya = ["apa", "siapa", "dimana", "mengapa",
              "bagaimana", "kapan", "berapa", "kenapa",
              "apakah", "siapakah", "dimanakah", "kapankah",
              "gak bahaya ta"
              ]

pertanyaan = input("Ketikkan kalimat: ")
pertanyaan = pertanyaan.lower()
pertanyaan = word_tokenize(pertanyaan)

print(pertanyaan)

#pertanyaan[0] berarti akan mengecek di kata awal apakah ada kata tanya disitu

if any(x in pertanyaan[0] for x in kata_tanya):
    print("Ini pertanyaan")
else:
    print("Ini bukan pertanyaan !!!")

"""# COBA-**2**"""

from nltk.tokenize import word_tokenize

def hapus_spasi_kata_tanya(kata_tanya):
    return [x.replace(" ", "") for x in kata_tanya]

kata_tanya = ["apa",
              "siapa",
              "dimana",
              "mengapa",
              "bagaimana",
              "kapan",
              "berapa",
              "kenapa",
              "apakah",
              "siapakah",
              "dimanakah",
              "kapankah",
              "gak bahaya ta"
              ]

kata_tanya = hapus_spasi_kata_tanya(kata_tanya)

pertanyaan = input("Ketikkan kalimat: ")
pertanyaan = pertanyaan.lower()
pertanyaan = word_tokenize(pertanyaan)

pertanyaan_tanpa_spasi = [x.replace(" ", "") for x in pertanyaan]

if any(x in pertanyaan_tanpa_spasi[0] for x in kata_tanya):
    print("Ini adalah pertanyaan")
else:
    print("Ini bukan pertanyaan !!!")

"""# COBA-**3**"""

def hapus_spasi_kata_tanya(kata_tanya):
    return [x.replace(" ", "") for x in kata_tanya]

kata_tanya = ["gak bahaya ta", "haruskah gitu"]
kata_tanya = hapus_spasi_kata_tanya(kata_tanya)
print(kata_tanya[0])

"""# COBA-**4**"""

def hapus_spasi_kata_tanya(kata_tanya):
    return [x.replace(" ", "") for x in kata_tanya]

def cari_indeks_kata_tanya(input_user, kata_tanya):
    input_user_tanpa_spasi = input_user.replace(" ", "")
    kata_tanya_tanpa_spasi = hapus_spasi_kata_tanya(kata_tanya)

    try:
        indeks = kata_tanya_tanpa_spasi.index(input_user_tanpa_spasi)
        return indeks
    except ValueError:
        return None

kata_tanya = ["gak bahaya ta", "haruskah gitu"]

input_user = input("Ketikkan input: ")

indeks = cari_indeks_kata_tanya(input_user, kata_tanya)
if indeks is not None:
    print(f"Input berada di indeks ke-{indeks} dalam list kata_tanya.")
else:
    print("Input tidak ditemukan dalam list kata_tanya.")

"""# COBA-**5**"""

def hapus_spasi_kata_tanya(kata_tanya):
    return [x.replace(" ", "") for x in kata_tanya]

def cari_indeks_kata_tanya(input_user, kata_tanya):
    input_user_tanpa_spasi = input_user.replace(" ", "")
    kata_tanya_tanpa_spasi = hapus_spasi_kata_tanya(kata_tanya)

    try:
        indeks = kata_tanya_tanpa_spasi.index(input_user_tanpa_spasi)
        return indeks
    except ValueError:
        return None

def tampilkan_indeks_kata_tanya(input_user, kata_tanya):
    indeks = cari_indeks_kata_tanya(input_user, kata_tanya)
    if indeks is not None:
        print(f"Kata '{input_user}' berada di indeks ke-{indeks} dalam list kata_tanya.")
    else:
        print(f"Kata '{input_user}' tidak ditemukan dalam list kata_tanya.")

kata_tanya = ["apa",
              "siapa",
              "dimana",
              "mengapa",
              "bagaimana",
              "kapan",
              "berapa",
              "kenapa",
              "apakah",
              "siapakah",
              "dimanakah",
              "kapankah",
              "gak bahaya ta",
              "haruskah gitu",
              "mananya",
              "dimananya"
              ]

kata_tanya = hapus_spasi_kata_tanya(kata_tanya)

print(kata_tanya)
print("\n")

input_user = input("Ketikkan kata tanya nya saja: ")

tampilkan_indeks_kata_tanya(input_user, kata_tanya)

print("\n")

pertanyaan = input("Ketikkan kalimat: ")
pertanyaan = pertanyaan.lower()
pertanyaan = word_tokenize(pertanyaan)

print(pertanyaan)
print("\n")
print(pertanyaan[0])

if any(x in pertanyaan[0] for x in kata_tanya):
    print("\nIni adalah pertanyaan")
else:
    print("\nIni bukan pertanyaan !!!")

"""# COBA-**7**
SUDAH FIX BENAR
"""

from nltk.tokenize import word_tokenize

### BY LAMDANI

def cek_pertanyaan(kalimat):
    return kalimat.endswith("?")

def hapus_spasi_kata_tanya(kata_tanya):
    return [x.replace(" ", "") for x in kata_tanya]

def cari_dan_gabungkan_kata(pertanyaan_1, kata_tanya):
    gabungkan_kata = "".join(pertanyaan_1)
    return gabungkan_kata

def gabungkan_string(question_1, pertanyaan_2):
    gabungan_kalimat = question_1 + " " + pertanyaan_2
    return gabungan_kalimat

def gabungkan_aja(gabungkan_kata, pertanyaan_2):
    gabungan_kalimatnya_dong = gabungkan_kata + " " + pertanyaan_2
    return gabungan_kalimatnya_dong

kata_tanya = ["apa",
              "apalah",
              "apa kah",

              "siapa",
              "siapa kah",

              "dimana",
              "dimana kah",
              "dimananya",

              "mengapa",
              "mengapa kah",
              "kenapa",
              "kenapa kah"

              "bagaimana",
              "bagaimana kah",
              "gimana",
              "gimana kah",

              "kapan",
              "kapan kah",

              "berapa",
              "berapa kah",

              "gak bahaya ta",

              "haruskah gitu",

              "mananya",

              "iya kah",

              "begitu kah",
              "gitu",
              "begitu",

              "begini kah",
              "gini",
              "begini"

              ]

#SUDAH DIHAPUS SETIAP KATA YANG DIDALAM LIST YANG MENGANDUNG SPASI
#CONTOH :
#begitu kah
# menjadi => begitukah
kata_tanya = hapus_spasi_kata_tanya(kata_tanya)
print(kata_tanya)
print("\n")

pertanyaan_1 = input("Ketikkan kalimat-1: ")
question_1 = pertanyaan_1
question_1 = question_1.lower()

pertanyaan_1 = pertanyaan_1.lower()
pertanyaan_1 = word_tokenize(pertanyaan_1)

# print("\n")
print(question_1)
print(pertanyaan_1)

pertanyaan_2 = input("\nKetikkan kalimat-2: ")
pertanyaan_2 = pertanyaan_2.lower()
print(pertanyaan_2)

gabungkan_kata = cari_dan_gabungkan_kata(pertanyaan_1, kata_tanya)
print("\nHasil penggabungan kalimat-1 menjadi 1 kata: ", gabungkan_kata)

hasil_gabungan    = gabungkan_string(question_1, pertanyaan_2)
hasil_gabungannya = gabungkan_aja(gabungkan_kata, pertanyaan_2)

print("\nGabungan kalimat-1 dan kalimat-2 (Versi 1) = ",hasil_gabungan)
print("Gabungan kalimat-1 dan kalimat-2 (Versi 2) = ",hasil_gabungannya)

if any(x in gabungkan_kata for x in kata_tanya):
    if cek_pertanyaan(hasil_gabungan):
      print("\nKESIMPULAN :\nKalimat tersebut adalah pertanyaan.")
    else:
      print("\nKESIMPULAN :\nKalimat tersebut bukan pertanyaan.")
else:
    print("\nKESIMPULAN :\nIni bukan pertanyaan !!!")

